// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevRainAPI.Models;

[Table("Feedback")]
public partial class Feedback
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid Id { get; set; }

    [Required]
    [Column("fullName")]
    [StringLength(255)]
    public string FullName { get; set; }

    [Required]
    [Column("email")]
    [StringLength(255)]
    public string Email { get; set; }

    [Required]
    [Column("company")]
    [StringLength(255)]
    public string Company { get; set; }

    [Required]
    [Column("text")]
    public string Text { get; set; }

    [Column("createdDate", TypeName = "date")]
    public DateOnly CreatedDate { get; set; }

    [Column("sentiment")]
    [StringLength(255)]
    public string Sentiment { get; set; }

    [Column("positiveScore", TypeName = "decimal(5, 2)")]
    public decimal? PositiveScore { get; set; }

    [Column("negativeScore", TypeName = "decimal(5, 2)")]
    public decimal? NegativeScore { get; set; }

    [Column("neutralScore", TypeName = "decimal(5, 2)")]
    public decimal? NeutralScore { get; set; }
}